//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5483
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSMSWebService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HSMS", Namespace="http://schemas.datacontract.org/2004/07/HSMSWebService")]
    public partial class HSMS : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescField;
        
        private int IDField;
        
        private string NumberField;
        
        private string OrganisationField;
        
        private string PriceField;
        
        private int PriorityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organisation
        {
            get
            {
                return this.OrganisationField;
            }
            set
            {
                this.OrganisationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHSMSService")]
public interface IHSMSService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHSMSService/GetAllActions", ReplyAction="http://tempuri.org/IHSMSService/GetAllActionsResponse")]
    HSMSWebService.HSMS[] GetAllActions();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHSMSService/GetActionsByPriority", ReplyAction="http://tempuri.org/IHSMSService/GetActionsByPriorityResponse")]
    HSMSWebService.HSMS[] GetActionsByPriority(int priority);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IHSMSServiceChannel : IHSMSService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class HSMSServiceClient : System.ServiceModel.ClientBase<IHSMSService>, IHSMSService
{
    
    public HSMSServiceClient()
    {
    }
    
    public HSMSServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HSMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HSMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HSMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public HSMSWebService.HSMS[] GetAllActions()
    {
        return base.Channel.GetAllActions();
    }
    
    public HSMSWebService.HSMS[] GetActionsByPriority(int priority)
    {
        return base.Channel.GetActionsByPriority(priority);
    }
}
